# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
  settings:
    govet:
      enable:
        - fieldalignment
    gosec:
      excludes:
        - G304 # File path provided as taint input - handled with #nosec comments where needed
    gocritic:
      disabled-checks:
        - ifElseChain # Complex conditionals are clearer as if-else than switch true
