version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: kportal
    main: ./cmd/kportal
    binary: kportal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.appVersion={{.Version}}

archives:
  - id: kportal
    formats: [tar.gz]
    name_template: "kportal-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "kportal-{{ .Version }}-checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge'
      - '^WIP'

release:
  github:
    owner: lukaszraczylo
    name: kportal
  name_template: "Release {{.Version}}"
  draft: false
  prerelease: auto

homebrew_casks:
  - repository:
      owner: lukaszraczylo
      name: homebrew-taps
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://lukaszraczylo.github.io/kportal
    description: "Modern Kubernetes port-forward manager with interactive TUI"
    license: MIT
    postflight: |
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/kportal"],
                     sudo: false
